### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by jekakiev** [technovangelist/airenamer#8]
Now here is new error
yevhenii@MBP-Yevhenii 253 % airenamer
Error: 404: Not Found
error: Uncaught (in promise) Error: Is a directory (os error 21): copy '/Users/yevhenii/Downloads/253/20240122135847873342000000-o.jpg' -> '/Users/yevhenii/Downloads/253/'
    at Object.copyFileSync (ext:deno_fs/30_fs.js:72:7)
    at file:///home/runner/work/airenamer/airenamer/main.ts:47:12
    at eventLoopTick (ext:core/01_core.js:183:11)
yevhenii@MBP-Yevhenii 253 %

**Comment by ACucos1** [comment]
Chances are your model is returning nothing for some reason so when the script copies your file it just ends up naming the copy as the directory because the name is blank. Make sure you pulled the LLM using `ollama pull [model-name]` and that Ollama is running on your system before running the `airename` command.

**Comment by technovangelist** [comment]
that’s gotta be that you don't have llava installed
it now checks for that
